### ISSUE TITLE
Error when typing (adding) text

### ISSUE THREAD

**Issue by dennislaupman** [y-js/y-text#9]
Hello,
I get an error when im typing text. Mostly after the second character:

![image](https://cloud.githubusercontent.com/assets/1274858/26632460/9053fbae-4610-11e7-8f79-202bdbcbf81c.png)

Grtz Dennis

PS. Problem get something todo with Y.Array ;)

**Comment by dmonad** [comment]
Hi Dennis,
This usually doesn't happen. Can you give me steps to reproduce the issue?

**Comment by dennislaupman** [comment]
The items array consists HTML nodes

```	  
Y({
	    db: {
	      name: 'memory' // store the shared data in memory
	    },
	    connector: {
	      name: 'websockets-client',
	      room: 'Textarea-example',            // Instances connected to the same room share data
	     // url: 'localhost:1234' // specify your own server destination
	    },
	    share: { // specify the shared content
	      array: 'Array', // y.share.array is of type Y.array
	      textarea: 'Text', // y.share.array is of type Y.array
	    },
	  }).then(function (y) {
	  	window.y = y;
		y.share.textarea.bind(items[0].querySelector('textarea'));		
	})
```

**Comment by dmonad** [comment]
The above code does not throw any errors for me. Please give me exact instructions to reproduce the issue.

You could also, for example, submit a .zip file containing a project that causes the issue.

**Comment by dennislaupman** [comment]
Hmzzz Weird! 

This is the config we're using in RadioManager:

  "yjs": "12.3.0",
    "y-websockets-client": "8.0.16",
    "y-array": "10.1.2",
    "y-map": "10.1.0",
    "y-text": "9.4.0",
    "y-richtext": "9.0.8",
    "y-memory": "8.0.8",

See also my prototype: 
https://we.tl/WMMxMKzWCQ

PS. Thanks for make the code readable in my previous post :) 

Grtz Dennis

**Comment by dmonad** [comment]
Hi Dennis,

I saw that you cloned the git repositories, instead of using a package manager. Since I do actively develop on the master branches, I strongly suggest you either use a package manager (e.g. bower, npm, ..), download the release from GitHub, or clone a tagged commit (not the master branch): 

```sh
# clone y-memory version 8.0.8
git clone -b 'v8.0.8' --single-branch --depth 1 https://github.com/y-js/y-memory.git
```

I experienced the same problem when running your project. But I didn't experience any problems when installing the packages using bower:

```sh
bower i yjs#12.3.0 y-array#10.1.2 y-map#10.1.0 y-memory#8.0.8 y-text#9.4.0 y-websockets-client#8.0.16
```

Update paths:
```html
<script src="bower_components/yjs/y.js" type="text/javascript"></script>
<script src="bower_components/y-memory/y-memory.js" type="text/javascript"></script>
<script src="bower_components/y-array/y-array.js" type="text/javascript"></script>
<script src="bower_components/y-text/y-text.js" type="text/javascript"></script>
<script src="bower_components/y-websockets-client/y-websockets-client.js" type="text/javascript">
```

So I'm certain you grabbed a buggy commit

**Comment by dennislaupman** [comment]
Thank you :)
